name: Sell
api: [3.0.0-ALPHA10, 3.0.0-ALPHA11, 3.0.0-ALPHA12]
main: SellHand\Main
version: 1.3.0
authors: [Muqsit, JackMD]
author: VMPE Development Team
commands:
  sell:
    description: "Sells the item in your hand or all of your inventory's contents"
    permission: sell.command
permissions:
  sell:
    default: true
    children:
      sell.hand:
        default: true
      sell.all:
        default: true
      sell.command:
        default: true
