name: SETVIP
main: MCPEVN\SetVip
version: 2.3
api: 3.0.0
author: MCPEVN TEAM
description: VIP plugin by MCPEVN Team COPYRIGHT
commands:
  setvip:
    description: SetRank Cho Người Chơi
  removevip:
    description: Xoá Rank Của Người Chơi
  voter:
    description: remove other player's vip status